/*static nested class:- A class inside a class which is having static modifier is called 
 *static nested class
 *
 *1) static class can only access static members of outer class
 *2) static declaration is possible: static variable, main method, static block
 *3) We can create object of inner class without using new keyword because of static class
 *eg:-Outer.Inner i = new Outer.Inner();
 **/

package com.java.type_of_classes;

public class StaticNestedClass_5 {};	// No use of the class only for class file naming purpose

class Outer7 {
	static int a=10;
	static int b=20;
	static class Inner7 {
		void disp() {
			System.out.println(a);	// non-static instance members are not allowed
			System.out.println(b);
		}
	}
	public static void main(String[] args) {
		new Outer7.Inner7().disp();
	}
}


// static nested class (static declaration is possible)
class Outer8 {
	static class Inner8 {
		static int a=100;
		public static void main(String[] args) {	//when we create the main method inside the inner class Outer8$Inner8.class file is generated by compiler.
			System.out.println("Inner class main method");
		}
		static
		{
			System.out.println("Inner class static block");
		}
	}
};